name=str(input("type your name : "))
age=int(input("type your age : "))
height=int(input("type your height : "))
print("name : ",name)
print("age : ",age)
print("height",height)
input("press enter to exit")
